name: CI

on: 
  pull_request:
    branches: master

jobs:
  pr_build:
    
    runs-on: ubuntu-latest
    name: Run PR tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: |
          echo "DOCKER_HOST_IP=127.0.0.1" >> .env
          docker-compose up -d
          docker exec -it kafka /bin/bash && ./opt/kafka/bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic test
