name: CI

on: 
  pull_request:
    branches: master

jobs:
  pr_build:
    
    runs-on: ubuntu-latest
    name: Run PR tests
    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
        ports: 
          - 2181:2181
        options: --name zookeeper

      kafka:
        image: wurstmeister/kafka:2.12-2.3.0
        env:
          KAFKA_ADVERTISED_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://kafka:19092,
                LISTENER_DOCKER_EXTERNAL://localhost:9092
          KAFKA_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://kafka:19092,
                LISTENER_DOCKER_EXTERNAL://:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
                LISTENER_DOCKER_INTERNAL:PLAINTEXT,
                LISTENER_DOCKER_EXTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_LOG4J_LOGGERS: >-
                kafka.controller=INFO,
                kafka.producer.async.DefaultEventHandler=INFO,
                state.change.logger=INFO
        ports:
          - 9092:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        options: --name kafka

      redis:
        options: --name redis
        image: redis
        ports:
          - "6379:6379"
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache maven repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Run tests
        run: |
          docker ps
          ./mvnw -B clean verify
