name: CI

on: 
  pull_request:
    branches: master

jobs:
  pr_build:
    
    runs-on: ubuntu-latest
    name: Run PR tests
    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
        ports: 
          - 2181:2181
        options: --name zookeeper

      kafka:
        image: wurstmeister/kafka:2.12-2.3.0
        env:
          KAFKA_ADVERTISED_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://localhost:19092,
                LISTENER_DOCKER_EXTERNAL://localhost:9092
          KAFKA_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://localhost:19092,
                LISTENER_DOCKER_EXTERNAL://:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
                LISTENER_DOCKER_INTERNAL:PLAINTEXT,
                LISTENER_DOCKER_EXTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_LOG4J_LOGGERS: >-
                kafka.controller=INFO,
                kafka.producer.async.DefaultEventHandler=INFO,
                state.change.logger=INFO
        ports:
          - 9092:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        options: --name kafka
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Run tests
        run: |
          docker ps
          docker exec -i kafka "./opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test"
          sleep 15000
