name: CI

on: 
  pull_request:
    branches: master

jobs:
  pr_build:
    
    runs-on: ubuntu-latest
    name: Test PR contents
    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
        ports: 
          - 2181:2181

      kafka:
        image: wurstmeister/kafka:2.12-2.3.0
        env:
          KAFKA_ADVERTISED_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://127.0.0.1:19092,
                LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
          KAFKA_LISTENERS: >-
                LISTENER_DOCKER_INTERNAL://127.0.0.1:19092,
                LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
                LISTENER_DOCKER_INTERNAL:PLAINTEXT,
                LISTENER_DOCKER_EXTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
          KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_LOG4J_LOGGERS: >-
                kafka.controller=INFO,
                kafka.producer.async.DefaultEventHandler=INFO,
                state.change.logger=INFO
        ports:
          - 9092:9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: |
          mvn -B clean verify
